export type ArabicCorpusKind = "equivalent" | "preserved";

export interface ArabicCorpusCase {
  readonly id: string;
  readonly input: string;
  readonly profiles: readonly string[];
  readonly expected: string;
  readonly kind: ArabicCorpusKind;
  readonly note: string;
}

/**
 * Curated JS/SQL equivalence corpus. Cases marked `preserved` document
 * transforms that v1 must not apply, including NFKC/presentation-form samples.
 */
export const ARABIC_NORMALIZATION_CORPUS: readonly ArabicCorpusCase[] = [
  {
    id: "msa-tatweel",
    input: "كتـــاب",
    profiles: ["arabic-basic"],
    expected: "كتاب",
    kind: "equivalent",
    note: "Modern Standard Arabic tatweel removal",
  },
  {
    id: "msa-fatha",
    input: "كَتاب",
    profiles: ["arabic-basic"],
    expected: "كتاب",
    kind: "equivalent",
    note: "common fatha removal",
  },
  {
    id: "msa-harakat-cluster",
    input: "الإِدَارَة",
    profiles: ["arabic-basic"],
    expected: "الادارة",
    kind: "equivalent",
    note: "alef-with-hamza-below plus kasra/fatha",
  },
  {
    id: "gulf-kuwait",
    input: "كُوَيْت",
    profiles: ["arabic-basic"],
    expected: "كويت",
    kind: "equivalent",
    note: "Gulf vocalized place name",
  },
  {
    id: "egyptian-masr",
    input: "مَصر",
    profiles: ["arabic-basic"],
    expected: "مصر",
    kind: "equivalent",
    note: "Egyptian common word",
  },
  {
    id: "name-ahmad",
    input: "أحمد",
    profiles: ["arabic-basic"],
    expected: "احمد",
    kind: "equivalent",
    note: "alef with hamza above in a name",
  },
  {
    id: "name-ibrahim",
    input: "إبراهيم",
    profiles: ["arabic-basic"],
    expected: "ابراهيم",
    kind: "equivalent",
    note: "alef with hamza below in a name",
  },
  {
    id: "brand-alef-madda",
    input: "آيفون",
    profiles: ["arabic-basic"],
    expected: "ايفون",
    kind: "equivalent",
    note: "alef with madda used in brand transliteration",
  },
  {
    id: "wasla",
    input: "ٱلرحمن",
    profiles: ["arabic-basic"],
    expected: "الرحمن",
    kind: "equivalent",
    note: "alef wasla",
  },
  {
    id: "alef-maqsura",
    input: "إلى",
    profiles: ["arabic-basic"],
    expected: "الي",
    kind: "equivalent",
    note: "alef maqsura → yeh",
  },
  {
    id: "superscript-alef",
    input: "هٰذا",
    profiles: ["arabic-basic"],
    expected: "هذا",
    kind: "equivalent",
    note: "superscript alef is a curated vocalization mark",
  },
  {
    id: "tanween-shadda-sukun",
    input: "كِتَابًا مُّدَرَّسْ",
    profiles: ["arabic-basic"],
    expected: "كتابا مدرس",
    kind: "equivalent",
    note: "tanween, shadda, and sukun",
  },
  {
    id: "mixed-sku",
    input: "SKU-آيفون",
    profiles: ["arabic-basic"],
    expected: "SKU-ايفون",
    kind: "equivalent",
    note: "mixed Arabic/English SKU",
  },
  {
    id: "already-normalized",
    input: "كتاب",
    profiles: ["arabic-basic"],
    expected: "كتاب",
    kind: "equivalent",
    note: "idempotent on already-normalized MSA",
  },
  {
    id: "english-unchanged",
    input: "iPhone 15",
    profiles: ["arabic-basic"],
    expected: "iPhone 15",
    kind: "equivalent",
    note: "Latin text is untouched",
  },
  {
    id: "empty",
    input: "",
    profiles: ["arabic-basic"],
    expected: "",
    kind: "equivalent",
    note: "empty string is identity",
  },
  {
    id: "preserve-teh-marbuta",
    input: "مدرسة",
    profiles: ["arabic-basic"],
    expected: "مدرسة",
    kind: "preserved",
    note: "ة → ه is not a default replacement",
  },
  {
    id: "preserve-waw-hamza",
    input: "مؤمن",
    profiles: ["arabic-basic"],
    expected: "مؤمن",
    kind: "preserved",
    note: "ؤ → و is not a default replacement",
  },
  {
    id: "preserve-yeh-hamza",
    input: "سائل",
    profiles: ["arabic-basic"],
    expected: "سائل",
    kind: "preserved",
    note: "ئ → ي is not a default replacement",
  },
  {
    id: "preserve-arabic-indic-digits",
    input: "١٢٣",
    profiles: ["arabic-basic"],
    expected: "١٢٣",
    kind: "preserved",
    note: "arabic-basic does not fold Arabic-Indic digits",
  },
  {
    id: "preserve-presentation-alef",
    input: "\uFE8D",
    profiles: ["arabic-basic"],
    expected: "\uFE8D",
    kind: "preserved",
    note: "compatibility presentation form is not NFKC-folded",
  },
  {
    id: "preserve-presentation-alef-hamza",
    input: "\uFE83",
    profiles: ["arabic-basic"],
    expected: "\uFE83",
    kind: "preserved",
    note: "presentation alef-with-hamza is not mapped to ا",
  },
  {
    id: "preserve-quranic-mark",
    input: "كتب\u06D6",
    profiles: ["arabic-basic"],
    expected: "كتب\u06D6",
    kind: "preserved",
    note: "Quranic annotation marks are unsupported edge cases, not normalized",
  },
  {
    id: "preserve-decomposed-hamza",
    input: "ا\u0654",
    profiles: ["arabic-basic"],
    expected: "ا\u0654",
    kind: "preserved",
    note: "combining hamza above is not stripped and is not NFC-composed to أ",
  },
  {
    id: "numeric-arabic-digits",
    input: "١٢٣",
    profiles: ["numeric-arabic"],
    expected: "123",
    kind: "equivalent",
    note: "optional numeric-arabic maps U+0660–U+0669",
  },
  {
    id: "numeric-arabic-sku",
    input: "SKU-١٢",
    profiles: ["numeric-arabic"],
    expected: "SKU-12",
    kind: "equivalent",
    note: "mixed SKU digit folding",
  },
  {
    id: "preserve-extended-persian-digits",
    input: "۰۱۲",
    profiles: ["numeric-arabic"],
    expected: "۰۱۲",
    kind: "preserved",
    note: "U+06F0–U+06F9 are outside the v1 numeric-arabic table",
  },
  {
    id: "composed-arabic-basic-numeric",
    input: "آيفون-١٢",
    profiles: ["arabic-basic", "numeric-arabic"],
    expected: "ايفون-12",
    kind: "equivalent",
    note: "declared profile order is applied left to right",
  },
];
